학습 목표 : Flow 사용 및 테스트 코드 작성하기
ParkChan/CleanArchitectureStudy_module_integration pull request #3
Opened 2021-12-02 12:11 UTC by ParkChan

### Todo
- 터빈을 이용하여 테스트 코드를 작성 하기

### Doing
- Flow 변경하기

테스트 코드는 곧이어 진행될 예정입니다.
flow로 변경한 코드에 대해서 리뷰를 받고 싶습니다.😊

2021-12-02 12:30 UTC, BeokBeok requested changes
작업하시느라 고생이 많으십니다.
약간의 코맨트를 작성하였습니다. :smile:

<details><summary>코드리뷰 우선순위 규칙 (P1~P3)</summary>
P1 > ★★★ : 적극적으로 고민해주세요 (Request changes)
<br>
코드 수정이 반드시 필요하다고 판단되는 경우입니다.<br>
리뷰 요청자께서 만약 수용할 수 없는 상황이라면 적합한 의견을 들어 토론해주세요.
<br></br>
P2 > ★★☆ : 웬만하면 반영해 주세요 (Comment)
<br>
코드 수정을 권장하거나 리뷰 요청자께서 해당 코드를 작성하신 의도를 알고자 하는 경우입니다.<br>
리뷰 요청자께서는 가급적이면 이유를 들어 설명해주시거나 의견을 달아주세요.
<br></br>
P3 > ★☆☆ : 반영해도 좋고 넘어가도 좋습니다 (Approve)
<br>
해당 의견을 반영하는 게 좋을지 고민해 보는 정도면 충분합니다.<br>
만약 리뷰 요청자께서 리뷰어의 의견을 반영하셨더라도 리뷰어에게 별도로 리뷰 요청을 드리지 않아도 됩니다.
</details>

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/data/source/MovieDataSourceImpl.kt
> +    override suspend fun fetchMovies(start: Int, query: String): Flow<MovieResponse> =
P1. flow는 suspend 함수가 아닙니다.
suspend를 제거해주세요

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +    }
```suggestion
    val searchQuery: StateFlow<String> get() = _searchQuery.asStateFlow()
```
P2. public getter를 활용하시면 좋을 것 같아요

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +        }
P1. init 블록에는 비즈니스 로직이 오지 않도록 해주세요.

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +        }
P1. 변수에는 행동보다는 상태를 저장해주세요.

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +    suspend fun fetchMovies(page: Int, query: String, isFirst: Boolean) =
P1. viewModelScope는 suspend 함수가 아닙니다.

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +    suspend fun moreMovies(query: String) {
P2. suspend 함수를 호출하지 마시고 viewModelScope를 통해서 호출해주시면 좋을 것 같아요

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +        private const val INTERVAL_KEYWORD_SEARCH = 1000L
```suggestion
        private const val INTERVAL_KEYWORD_SEARCH = 1_000L
```
P3. 언더바를 사용하면 가독성이 좋아져요

2021-12-02 12:30 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
> +                    }
P2. launchWhenXXX 시리즈는 사용하지 않는 것이 좋습니다.

ref. https://hongbeomi.medium.com/%EB%B2%88%EC%97%AD-android-ui%EC%97%90%EC%84%9C-flow%EB%A5%BC-%EC%88%98%EC%A7%91%ED%95%98%EB%8A%94-%EC%95%88%EC%A0%84%ED%95%9C-%EA%B8%B8-bd8449e67ec3

2021-12-02 15:26 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
> +                    }
사용을 안해봐서 써보고 싶어서 한것인데 별로군요 🤣

2021-12-02 15:38 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
> +                    }
b0b49666f675962e22b2099d623f1764280ee4c6 
이런 문제가 있을 줄은 상상도 못했습니다.
launchWhenStarted 를 job으로 취소해주거나 repeatOnLifecycle 를 사용하는 방법등... 
내용 잘 보았습니다. 이런 복잡한 기능을 사용하는것보다 
올바른 뷰 생명주기안에서 호출하는 것이 좋겠네요!👍

2021-12-02 15:39 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +        private const val INTERVAL_KEYWORD_SEARCH = 1000L
04beed279cccc4090dde733691ed2a20360a2f3f 이런 기본을 놓치다니!!🤣 피드백 감사합니다.

2021-12-02 15:39 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +    suspend fun moreMovies(query: String) {
6f680f25874203a1b31a2b94264a3a5d5a8223e3 viewModelScope 를 통해서 호출 하도록 수정하였습니다.

2021-12-02 15:40 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +    suspend fun fetchMovies(page: Int, query: String, isFirst: Boolean) =
7d0903863f2cfacd292132c9cc250cd92fd15f17 코드를 이리저리 수정하다보니 이상한녀석이 탄생했었네요. 수정하였습니다.

2021-12-02 15:40 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +    }
67dd5cf656b6fc335dc675cbba99a59295720638 debunce에 대한 처리를 뷰로 이관하면서 삭제하였습니다.

2021-12-02 15:44 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/data/source/MovieDataSourceImpl.kt
> +    override suspend fun fetchMovies(start: Int, query: String): Flow<MovieResponse> =
2c5ee6b69ce7d80f5e827474e81a885f856ba2ed  suspend 를 제거하였습니다.👍

2021-12-02 15:45 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +        }
41e80752e1f119f3ed32ab26376ed54efc5a3720 init 블록에 있는 로직을 삭제하였습니다.

2021-12-02 15:46 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/MovieSearchViewModel.kt
> +        }
67dd5cf656b6fc335dc675cbba99a59295720638 debounce에 대한 처리를 View 로직으로 이관하면서 해당 변수를 삭제하였습니다.

2021-12-03 12:12 UTC, BeokBeok requested changes

2021-12-03 12:12 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/MainActivity.kt
> +        const val VIEWPAGER_OFFSCREEN_PAGE_LIMIT = 1
P1. 내부에서만 사용하는 변수라면 private 접근자를 사용해주세요

2021-12-03 12:12 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
>      }
P2. 리스너를 onResume에서 등록해주는 이유가 있을까요?

2021-12-03 18:13 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
>      }
[스택오버플로우 링크주소](https://stackoverflow.com/questions/45035804/ontextchanged-is-triggered-on-orientationchange-even-if-textwatcher-is-set-after)
화면 회전 시 EditText의 watcher 가 트리거 되는 문제였는데 onResume은 잘못된 위치 같습니다🤣

현재 onStart()로 옮겨서 문제가 없지만 이 또한 좋은 방법은 아닌 것 같습니다.

watcher 를 변수로 두어 addTextChangedListener(), removeTextChangedListener() 를 해주는것이 바람직해 보이는데

아래 코드때문에 어떻게 적용하면 좋을지 고민이 드네요 😂
```
fun EditText.textInputAsFlow() = callbackFlow {
    val watcher: TextWatcher = doOnTextChanged { textInput: CharSequence?, _, _, _ ->
        trySend(textInput)
    }
    awaitClose { this@textInputAsFlow.removeTextChangedListener(watcher) }
}

```

2021-12-03 18:14 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/MainActivity.kt
> +        const val VIEWPAGER_OFFSCREEN_PAGE_LIMIT = 1
f8d81b1e95993adb7affbbb0286fe68425424eb2 private 접근자로 수정하였습니다.

2021-12-04 11:26 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
>      }
단순히 리스너를 등록하는 부분이기 때문에, onCreate쪽에 하면 되지 않을까요?

2021-12-04 18:02 UTC, ParkChan commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
>      }
65845ea648666060e98c05512ef55dc5a481c4e3 onCeate 에서 등록하는것으로 수정하였습니다~!
단 화면 회전시 EditText의 watcher가 동작하면 검색이 일어나는 문제가 있어서 
viewModel 로직에서 같은 키워드로 검색이 수행되면 검색이 재요청되지 않도록 beforeText를 추가해 주었습니다.

번외로 EditText는 화면회전이 되면 어떻게 데이터가 유지가 되지?라는 의문점이 생겨 자료를 찾아보니 
![image](https://user-images.githubusercontent.com/7857824/144719624-117e6372-2d75-4e7d-b026-b2d29eb7cca8.png)
이런 내용이 있네요. 혹시나 도움이 될 자료일까 싶어 공유 드립니다~!

2021-12-05 02:31 UTC, BeokBeok commented on feature/movie/src/main/java/com/chan/movie/ui/main/fragment/SearchListFragment.kt
>      }
사실 주로 화면을 고정한 상태로 작업을 해서 이 부분은 저도 잘 모르겠네요 😭 
onConfigurationChanged 를 활용해서 화면 회전 시 EditText의 포커스를 클리어하면 되지 않을까요? 🤔 

> 번외로 EditText는 화면회전이 되면 어떻게 입력된 데이터가 어떻게 유지가 되는거지?라는
의문점이 생겨 자료를 찾아보니

View에 id를 정의하게 되면, 내부적으로 View의 상태를 유지합니다.
ref1. https://developer.android.com/guide/components/activities/activity-lifecycle#onstop
ref2. https://developer.android.com/guide/components/activities/activity-lifecycle#instance-state

2021-12-05 02:33 UTC, BeokBeok approved these changes
<img src="https://user-images.githubusercontent.com/48344355/108810482-8fca5400-75ee-11eb-9a24-9931a3877f9d.png" width="30%">

2021-12-05 08:46 UTC, ParkChan commented
![108810482-8fca5400-75ee-11eb-9a24-9931a3877f9d](https://user-images.githubusercontent.com/7857824/144739803-e88cba01-71c5-4094-a577-1406bd9300d7.png)

알려주신 깃헙의 리플 기능을 사용해보았어요 😊

2021-12-05 08:47 UTC, merged